// Copies the compiled StandIn ABI into the app so the two never drift.
// Run after `forge build`: node scripts/sync-abi.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = JSON.parse(readFileSync(join(root, "contracts/out/StandIn.sol/StandIn.json"), "utf8"));
const out = join(root, "app/src/lib/standin-abi.ts");

writeFileSync(
  out,
  `// Generated by scripts/sync-abi.mjs from contracts/out/StandIn.sol/StandIn.json. Do not edit.\n` +
    `export const standInAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);
console.log(`wrote ${out} (${artifact.abi.length} entries)`);
